package com.educareapps.quiz.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CSVQUESTION_TABLE".
 */
public class CSVQuestionTable {

    private Long id;
    private long question_id;
    /** Not-null value. */
    private String question;
    /** Not-null value. */
    private String option_one;
    /** Not-null value. */
    private String option_two;
    /** Not-null value. */
    private String option_three;
    /** Not-null value. */
    private String option_four;
    /** Not-null value. */
    private String answer;
    private long question_set_id;

    public CSVQuestionTable() {
    }

    public CSVQuestionTable(Long id) {
        this.id = id;
    }

    public CSVQuestionTable(Long id, long question_id, String question, String option_one, String option_two, String option_three, String option_four, String answer, long question_set_id) {
        this.id = id;
        this.question_id = question_id;
        this.question = question;
        this.option_one = option_one;
        this.option_two = option_two;
        this.option_three = option_three;
        this.option_four = option_four;
        this.answer = answer;
        this.question_set_id = question_set_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getQuestion_id() {
        return question_id;
    }

    public void setQuestion_id(long question_id) {
        this.question_id = question_id;
    }

    /** Not-null value. */
    public String getQuestion() {
        return question;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQuestion(String question) {
        this.question = question;
    }

    /** Not-null value. */
    public String getOption_one() {
        return option_one;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOption_one(String option_one) {
        this.option_one = option_one;
    }

    /** Not-null value. */
    public String getOption_two() {
        return option_two;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOption_two(String option_two) {
        this.option_two = option_two;
    }

    /** Not-null value. */
    public String getOption_three() {
        return option_three;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOption_three(String option_three) {
        this.option_three = option_three;
    }

    /** Not-null value. */
    public String getOption_four() {
        return option_four;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOption_four(String option_four) {
        this.option_four = option_four;
    }

    /** Not-null value. */
    public String getAnswer() {
        return answer;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public long getQuestion_set_id() {
        return question_set_id;
    }

    public void setQuestion_set_id(long question_set_id) {
        this.question_set_id = question_set_id;
    }

}
