package com.educareapps.quiz.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CSVQUESTION_TABLE".
 */
public class CSVQuestionTable {

    private Long id;
    /** Not-null value. */
    private String csv_id;
    /** Not-null value. */
    private String ques_set_id;
    /** Not-null value. */
    private String question;
    /** Not-null value. */
    private String option_1;
    /** Not-null value. */
    private String option_2;
    /** Not-null value. */
    private String option_3;
    /** Not-null value. */
    private String option_4;
    /** Not-null value. */
    private String answer;

    public CSVQuestionTable() {
    }

    public CSVQuestionTable(Long id) {
        this.id = id;
    }

    public CSVQuestionTable(Long id, String csv_id, String ques_set_id, String question, String option_1, String option_2, String option_3, String option_4, String answer) {
        this.id = id;
        this.csv_id = csv_id;
        this.ques_set_id = ques_set_id;
        this.question = question;
        this.option_1 = option_1;
        this.option_2 = option_2;
        this.option_3 = option_3;
        this.option_4 = option_4;
        this.answer = answer;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCsv_id() {
        return csv_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCsv_id(String csv_id) {
        this.csv_id = csv_id;
    }

    /** Not-null value. */
    public String getQues_set_id() {
        return ques_set_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQues_set_id(String ques_set_id) {
        this.ques_set_id = ques_set_id;
    }

    /** Not-null value. */
    public String getQuestion() {
        return question;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQuestion(String question) {
        this.question = question;
    }

    /** Not-null value. */
    public String getOption_1() {
        return option_1;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOption_1(String option_1) {
        this.option_1 = option_1;
    }

    /** Not-null value. */
    public String getOption_2() {
        return option_2;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOption_2(String option_2) {
        this.option_2 = option_2;
    }

    /** Not-null value. */
    public String getOption_3() {
        return option_3;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOption_3(String option_3) {
        this.option_3 = option_3;
    }

    /** Not-null value. */
    public String getOption_4() {
        return option_4;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOption_4(String option_4) {
        this.option_4 = option_4;
    }

    /** Not-null value. */
    public String getAnswer() {
        return answer;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

}
