package com.educareapps.quiz.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.educareapps.quiz.dao.CSVQuestionTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CSVQUESTION_TABLE".
*/
public class CSVQuestionTableDao extends AbstractDao<CSVQuestionTable, Long> {

    public static final String TABLENAME = "CSVQUESTION_TABLE";

    /**
     * Properties of entity CSVQuestionTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Csv_id = new Property(1, String.class, "csv_id", false, "CSV_ID");
        public final static Property Ques_set_id = new Property(2, String.class, "ques_set_id", false, "QUES_SET_ID");
        public final static Property Question = new Property(3, String.class, "question", false, "QUESTION");
        public final static Property Option_1 = new Property(4, String.class, "option_1", false, "OPTION_1");
        public final static Property Option_2 = new Property(5, String.class, "option_2", false, "OPTION_2");
        public final static Property Option_3 = new Property(6, String.class, "option_3", false, "OPTION_3");
        public final static Property Option_4 = new Property(7, String.class, "option_4", false, "OPTION_4");
        public final static Property Answer = new Property(8, String.class, "answer", false, "ANSWER");
    };


    public CSVQuestionTableDao(DaoConfig config) {
        super(config);
    }
    
    public CSVQuestionTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CSVQUESTION_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CSV_ID\" TEXT NOT NULL ," + // 1: csv_id
                "\"QUES_SET_ID\" TEXT NOT NULL ," + // 2: ques_set_id
                "\"QUESTION\" TEXT NOT NULL ," + // 3: question
                "\"OPTION_1\" TEXT NOT NULL ," + // 4: option_1
                "\"OPTION_2\" TEXT NOT NULL ," + // 5: option_2
                "\"OPTION_3\" TEXT NOT NULL ," + // 6: option_3
                "\"OPTION_4\" TEXT NOT NULL ," + // 7: option_4
                "\"ANSWER\" TEXT NOT NULL );"); // 8: answer
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CSVQUESTION_TABLE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CSVQuestionTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getCsv_id());
        stmt.bindString(3, entity.getQues_set_id());
        stmt.bindString(4, entity.getQuestion());
        stmt.bindString(5, entity.getOption_1());
        stmt.bindString(6, entity.getOption_2());
        stmt.bindString(7, entity.getOption_3());
        stmt.bindString(8, entity.getOption_4());
        stmt.bindString(9, entity.getAnswer());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CSVQuestionTable readEntity(Cursor cursor, int offset) {
        CSVQuestionTable entity = new CSVQuestionTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // csv_id
            cursor.getString(offset + 2), // ques_set_id
            cursor.getString(offset + 3), // question
            cursor.getString(offset + 4), // option_1
            cursor.getString(offset + 5), // option_2
            cursor.getString(offset + 6), // option_3
            cursor.getString(offset + 7), // option_4
            cursor.getString(offset + 8) // answer
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CSVQuestionTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCsv_id(cursor.getString(offset + 1));
        entity.setQues_set_id(cursor.getString(offset + 2));
        entity.setQuestion(cursor.getString(offset + 3));
        entity.setOption_1(cursor.getString(offset + 4));
        entity.setOption_2(cursor.getString(offset + 5));
        entity.setOption_3(cursor.getString(offset + 6));
        entity.setOption_4(cursor.getString(offset + 7));
        entity.setAnswer(cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CSVQuestionTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CSVQuestionTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
