package com.educareapps.quiz.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.educareapps.quiz.dao.UserTableDao;
import com.educareapps.quiz.dao.LanguageTableDao;
import com.educareapps.quiz.dao.QuestionSetTableDao;
import com.educareapps.quiz.dao.CSVQuestionTableDao;
import com.educareapps.quiz.dao.TestTableDao;
import com.educareapps.quiz.dao.LeaderBoardTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        UserTableDao.createTable(db, ifNotExists);
        LanguageTableDao.createTable(db, ifNotExists);
        QuestionSetTableDao.createTable(db, ifNotExists);
        CSVQuestionTableDao.createTable(db, ifNotExists);
        TestTableDao.createTable(db, ifNotExists);
        LeaderBoardTableDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        UserTableDao.dropTable(db, ifExists);
        LanguageTableDao.dropTable(db, ifExists);
        QuestionSetTableDao.dropTable(db, ifExists);
        CSVQuestionTableDao.dropTable(db, ifExists);
        TestTableDao.dropTable(db, ifExists);
        LeaderBoardTableDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(UserTableDao.class);
        registerDaoClass(LanguageTableDao.class);
        registerDaoClass(QuestionSetTableDao.class);
        registerDaoClass(CSVQuestionTableDao.class);
        registerDaoClass(TestTableDao.class);
        registerDaoClass(LeaderBoardTableDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
