package com.educareapps.quiz.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.educareapps.quiz.dao.User;
import com.educareapps.quiz.dao.CSVQuestionTable;

import com.educareapps.quiz.dao.UserDao;
import com.educareapps.quiz.dao.CSVQuestionTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig cSVQuestionTableDaoConfig;

    private final UserDao userDao;
    private final CSVQuestionTableDao cSVQuestionTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        cSVQuestionTableDaoConfig = daoConfigMap.get(CSVQuestionTableDao.class).clone();
        cSVQuestionTableDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        cSVQuestionTableDao = new CSVQuestionTableDao(cSVQuestionTableDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(CSVQuestionTable.class, cSVQuestionTableDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        cSVQuestionTableDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public CSVQuestionTableDao getCSVQuestionTableDao() {
        return cSVQuestionTableDao;
    }

}
