package com.educareapps.quiz.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.educareapps.quiz.dao.LanguageTable;
import com.educareapps.quiz.dao.QuestionSetTable;
import com.educareapps.quiz.dao.CSVQuestionTable;

import com.educareapps.quiz.dao.LanguageTableDao;
import com.educareapps.quiz.dao.QuestionSetTableDao;
import com.educareapps.quiz.dao.CSVQuestionTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig languageTableDaoConfig;
    private final DaoConfig questionSetTableDaoConfig;
    private final DaoConfig cSVQuestionTableDaoConfig;

    private final LanguageTableDao languageTableDao;
    private final QuestionSetTableDao questionSetTableDao;
    private final CSVQuestionTableDao cSVQuestionTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        languageTableDaoConfig = daoConfigMap.get(LanguageTableDao.class).clone();
        languageTableDaoConfig.initIdentityScope(type);

        questionSetTableDaoConfig = daoConfigMap.get(QuestionSetTableDao.class).clone();
        questionSetTableDaoConfig.initIdentityScope(type);

        cSVQuestionTableDaoConfig = daoConfigMap.get(CSVQuestionTableDao.class).clone();
        cSVQuestionTableDaoConfig.initIdentityScope(type);

        languageTableDao = new LanguageTableDao(languageTableDaoConfig, this);
        questionSetTableDao = new QuestionSetTableDao(questionSetTableDaoConfig, this);
        cSVQuestionTableDao = new CSVQuestionTableDao(cSVQuestionTableDaoConfig, this);

        registerDao(LanguageTable.class, languageTableDao);
        registerDao(QuestionSetTable.class, questionSetTableDao);
        registerDao(CSVQuestionTable.class, cSVQuestionTableDao);
    }
    
    public void clear() {
        languageTableDaoConfig.getIdentityScope().clear();
        questionSetTableDaoConfig.getIdentityScope().clear();
        cSVQuestionTableDaoConfig.getIdentityScope().clear();
    }

    public LanguageTableDao getLanguageTableDao() {
        return languageTableDao;
    }

    public QuestionSetTableDao getQuestionSetTableDao() {
        return questionSetTableDao;
    }

    public CSVQuestionTableDao getCSVQuestionTableDao() {
        return cSVQuestionTableDao;
    }

}
