package com.educareapps.quiz.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.educareapps.quiz.dao.LanguageTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LANGUAGE_TABLE".
*/
public class LanguageTableDao extends AbstractDao<LanguageTable, Long> {

    public static final String TABLENAME = "LANGUAGE_TABLE";

    /**
     * Properties of entity LanguageTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Lang_id = new Property(1, long.class, "lang_id", false, "LANG_ID");
        public final static Property Lang_name = new Property(2, String.class, "lang_name", false, "LANG_NAME");
        public final static Property Status = new Property(3, String.class, "status", false, "STATUS");
        public final static Property Created_at = new Property(4, String.class, "created_at", false, "CREATED_AT");
        public final static Property Question_set_id = new Property(5, long.class, "question_set_id", false, "QUESTION_SET_ID");
    };

    private Query<LanguageTable> questionSetTable_QuestoinSetToLanguageQuery;

    public LanguageTableDao(DaoConfig config) {
        super(config);
    }
    
    public LanguageTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LANGUAGE_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"LANG_ID\" INTEGER NOT NULL ," + // 1: lang_id
                "\"LANG_NAME\" TEXT NOT NULL ," + // 2: lang_name
                "\"STATUS\" TEXT NOT NULL ," + // 3: status
                "\"CREATED_AT\" TEXT NOT NULL ," + // 4: created_at
                "\"QUESTION_SET_ID\" INTEGER NOT NULL );"); // 5: question_set_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LANGUAGE_TABLE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LanguageTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getLang_id());
        stmt.bindString(3, entity.getLang_name());
        stmt.bindString(4, entity.getStatus());
        stmt.bindString(5, entity.getCreated_at());
        stmt.bindLong(6, entity.getQuestion_set_id());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public LanguageTable readEntity(Cursor cursor, int offset) {
        LanguageTable entity = new LanguageTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // lang_id
            cursor.getString(offset + 2), // lang_name
            cursor.getString(offset + 3), // status
            cursor.getString(offset + 4), // created_at
            cursor.getLong(offset + 5) // question_set_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LanguageTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLang_id(cursor.getLong(offset + 1));
        entity.setLang_name(cursor.getString(offset + 2));
        entity.setStatus(cursor.getString(offset + 3));
        entity.setCreated_at(cursor.getString(offset + 4));
        entity.setQuestion_set_id(cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(LanguageTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(LanguageTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "questoinSetToLanguage" to-many relationship of QuestionSetTable. */
    public List<LanguageTable> _queryQuestionSetTable_QuestoinSetToLanguage(long question_set_id) {
        synchronized (this) {
            if (questionSetTable_QuestoinSetToLanguageQuery == null) {
                QueryBuilder<LanguageTable> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Question_set_id.eq(null));
                questionSetTable_QuestoinSetToLanguageQuery = queryBuilder.build();
            }
        }
        Query<LanguageTable> query = questionSetTable_QuestoinSetToLanguageQuery.forCurrentThread();
        query.setParameter(0, question_set_id);
        return query.list();
    }

}
