package com.educareapps.quiz.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LANGUAGE_TABLE".
 */
public class LanguageTable {

    private Long id;
    private long lang_id;
    /** Not-null value. */
    private String lang_name;
    /** Not-null value. */
    private String status;
    /** Not-null value. */
    private String created_at;
    private long question_set_id;

    public LanguageTable() {
    }

    public LanguageTable(Long id) {
        this.id = id;
    }

    public LanguageTable(Long id, long lang_id, String lang_name, String status, String created_at, long question_set_id) {
        this.id = id;
        this.lang_id = lang_id;
        this.lang_name = lang_name;
        this.status = status;
        this.created_at = created_at;
        this.question_set_id = question_set_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getLang_id() {
        return lang_id;
    }

    public void setLang_id(long lang_id) {
        this.lang_id = lang_id;
    }

    /** Not-null value. */
    public String getLang_name() {
        return lang_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLang_name(String lang_name) {
        this.lang_name = lang_name;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

    /** Not-null value. */
    public String getCreated_at() {
        return created_at;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public long getQuestion_set_id() {
        return question_set_id;
    }

    public void setQuestion_set_id(long question_set_id) {
        this.question_set_id = question_set_id;
    }

}
