package com.educareapps.quiz.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.educareapps.quiz.dao.QuestionSetTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "QUESTION_SET_TABLE".
*/
public class QuestionSetTableDao extends AbstractDao<QuestionSetTable, Long> {

    public static final String TABLENAME = "QUESTION_SET_TABLE";

    /**
     * Properties of entity QuestionSetTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Question_set_id = new Property(1, long.class, "question_set_id", false, "QUESTION_SET_ID");
        public final static Property Question_set = new Property(2, String.class, "question_set", false, "QUESTION_SET");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property Photo = new Property(4, String.class, "photo", false, "PHOTO");
        public final static Property Created_at = new Property(5, String.class, "created_at", false, "CREATED_AT");
        public final static Property Question_id = new Property(6, long.class, "question_id", false, "QUESTION_ID");
    };

    private DaoSession daoSession;

    private Query<QuestionSetTable> cSVQuestionTable_CSVQuestionToquestionSetQuery;

    public QuestionSetTableDao(DaoConfig config) {
        super(config);
    }
    
    public QuestionSetTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"QUESTION_SET_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"QUESTION_SET_ID\" INTEGER NOT NULL ," + // 1: question_set_id
                "\"QUESTION_SET\" TEXT NOT NULL ," + // 2: question_set
                "\"TITLE\" TEXT NOT NULL ," + // 3: title
                "\"PHOTO\" TEXT NOT NULL ," + // 4: photo
                "\"CREATED_AT\" TEXT NOT NULL ," + // 5: created_at
                "\"QUESTION_ID\" INTEGER NOT NULL );"); // 6: question_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"QUESTION_SET_TABLE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, QuestionSetTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getQuestion_set_id());
        stmt.bindString(3, entity.getQuestion_set());
        stmt.bindString(4, entity.getTitle());
        stmt.bindString(5, entity.getPhoto());
        stmt.bindString(6, entity.getCreated_at());
        stmt.bindLong(7, entity.getQuestion_id());
    }

    @Override
    protected void attachEntity(QuestionSetTable entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public QuestionSetTable readEntity(Cursor cursor, int offset) {
        QuestionSetTable entity = new QuestionSetTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // question_set_id
            cursor.getString(offset + 2), // question_set
            cursor.getString(offset + 3), // title
            cursor.getString(offset + 4), // photo
            cursor.getString(offset + 5), // created_at
            cursor.getLong(offset + 6) // question_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, QuestionSetTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQuestion_set_id(cursor.getLong(offset + 1));
        entity.setQuestion_set(cursor.getString(offset + 2));
        entity.setTitle(cursor.getString(offset + 3));
        entity.setPhoto(cursor.getString(offset + 4));
        entity.setCreated_at(cursor.getString(offset + 5));
        entity.setQuestion_id(cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(QuestionSetTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(QuestionSetTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "CSVQuestionToquestionSet" to-many relationship of CSVQuestionTable. */
    public List<QuestionSetTable> _queryCSVQuestionTable_CSVQuestionToquestionSet(long question_id) {
        synchronized (this) {
            if (cSVQuestionTable_CSVQuestionToquestionSetQuery == null) {
                QueryBuilder<QuestionSetTable> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Question_id.eq(null));
                cSVQuestionTable_CSVQuestionToquestionSetQuery = queryBuilder.build();
            }
        }
        Query<QuestionSetTable> query = cSVQuestionTable_CSVQuestionToquestionSetQuery.forCurrentThread();
        query.setParameter(0, question_id);
        return query.list();
    }

}
